-- Dispatch one editor text-correction request immediately after the comment.
-- The GitHub Actions token stays in Supabase Vault; no token is stored in code.
begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to postgres, service_role;

create table if not exists private.editorial_correction_dispatch_log (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null references public.editorial_feedback(id) on delete cascade,
  invoked_at timestamptz not null default now(),
  status text not null,
  request_id bigint,
  detail text,
  constraint editorial_correction_dispatch_status_valid
    check (status in (
      'queued',
      'skipped_no_token',
      'skipped_not_pending',
      'error'
    ))
);

create index if not exists editorial_correction_dispatch_feedback_idx
  on private.editorial_correction_dispatch_log (feedback_id, id desc);

create unique index if not exists editorial_correction_dispatch_queued_once
  on private.editorial_correction_dispatch_log (feedback_id)
  where status = 'queued';

alter table private.editorial_correction_dispatch_log enable row level security;
revoke all on table private.editorial_correction_dispatch_log
  from public, anon, authenticated;
grant select on table private.editorial_correction_dispatch_log to service_role;
grant usage, select on sequence private.editorial_correction_dispatch_log_id_seq
  to service_role;

create or replace function private.dispatch_editorial_correction(
  p_feedback_id bigint
)
returns text
language plpgsql
security definer
set search_path = pg_catalog, private, vault, net, public
as $function$
declare
  feedback_type text;
  feedback_status text;
  github_token text;
  request_id bigint;
begin
  if p_feedback_id is null or p_feedback_id <= 0 then
    return 'invalid_id';
  end if;

  -- Prevent two webhook retries or manual retries from dispatching the same
  -- feedback request at the same time.
  perform pg_advisory_xact_lock(p_feedback_id);

  select ef.feedback_type, ef.status
    into feedback_type, feedback_status
    from public.editorial_feedback ef
   where ef.id = p_feedback_id;

  if not found then
    return 'not_found';
  end if;

  if feedback_type <> 'text_correction'
     or feedback_status <> 'pending_processing' then
    insert into private.editorial_correction_dispatch_log (
      feedback_id, status, detail
    )
    values (
      p_feedback_id,
      'skipped_not_pending',
      format('Expected text_correction/pending_processing, got %s/%s',
        feedback_type, feedback_status)
    );
    return 'skipped_not_pending';
  end if;

  if exists (
    select 1
      from private.editorial_correction_dispatch_log
     where feedback_id = p_feedback_id
       and status = 'queued'
  ) then
    return 'queued';
  end if;

  select decrypted_secret
    into github_token
    from vault.decrypted_secrets
   where name = 'github_actions_token'
   limit 1;

  if coalesce(btrim(github_token), '') = '' then
    insert into private.editorial_correction_dispatch_log (
      feedback_id, status, detail
    )
    values (
      p_feedback_id,
      'skipped_no_token',
      'Vault secret github_actions_token is not configured'
    );
    return 'skipped_no_token';
  end if;

  select net.http_post(
    url := 'https://api.github.com/repos/iazenin88-lang/belgium-news-bot/actions/workflows/editorial_correction.yml/dispatches',
    headers := jsonb_build_object(
      'Accept', 'application/vnd.github+json',
      'Authorization', 'Bearer ' || github_token,
      'Content-Type', 'application/json',
      'User-Agent', 'belgium-news-supabase-webhook',
      'X-GitHub-Api-Version', '2022-11-28'
    ),
    body := jsonb_build_object(
      'ref', 'main',
      'inputs', jsonb_build_object('feedback_id', p_feedback_id::text)
    ),
    timeout_milliseconds := 5000
  )
    into request_id;

  insert into private.editorial_correction_dispatch_log (
    feedback_id, status, request_id, detail
  )
  values (
    p_feedback_id,
    'queued',
    request_id,
    'GitHub editorial correction workflow queued through pg_net'
  );
  return 'queued';
exception
  when others then
    insert into private.editorial_correction_dispatch_log (
      feedback_id, status, detail
    )
    values (p_feedback_id, 'error', sqlerrm);
    return 'error';
end;
$function$;

revoke all on function private.dispatch_editorial_correction(bigint)
  from public, anon, authenticated;
grant execute on function private.dispatch_editorial_correction(bigint)
  to postgres, service_role;

-- PostgREST exposes the wrapper through public schema, but only the backend
-- service role can execute it.
create or replace function public.dispatch_editorial_correction(
  p_feedback_id bigint
)
returns text
language sql
security invoker
set search_path = pg_catalog, public, private
as $function$
  select private.dispatch_editorial_correction(p_feedback_id);
$function$;

revoke all on function public.dispatch_editorial_correction(bigint)
  from public, anon, authenticated;
grant execute on function public.dispatch_editorial_correction(bigint)
  to service_role;

commit;
