-- Versioned pre-filter learning with explicit Telegram approval.
begin;

create table public.prefilter_policy_proposals (
  id bigint generated by default as identity primary key,
  status text not null default 'pending',
  summary text not null,
  rationale text not null,
  policy jsonb not null,
  metrics jsonb not null default '{}'::jsonb,
  training_decisions integer not null,
  training_approvals integer not null,
  training_topic_declines integer not null,
  model text not null,
  telegram_chat_id bigint,
  telegram_message_id bigint,
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by bigint,
  constraint prefilter_policy_status_valid
    check (status in ('pending', 'active', 'rejected', 'superseded')),
  constraint prefilter_policy_training_positive check (training_decisions >= 0),
  constraint prefilter_policy_shape check (
    jsonb_typeof(policy->'positive_terms') = 'array'
    and jsonb_typeof(policy->'negative_terms') = 'array'
  )
);

create unique index prefilter_policy_one_pending
  on public.prefilter_policy_proposals ((status))
  where status = 'pending';
create unique index prefilter_policy_one_active
  on public.prefilter_policy_proposals ((status))
  where status = 'active';

create table public.prefilter_settings (
  id smallint primary key default 1 check (id = 1),
  learning_mode boolean not null default true,
  minimum_training_decisions integer not null default 50
    check (minimum_training_decisions between 20 and 500),
  decisions_at_last_proposal integer not null default 0,
  current_policy_id bigint references public.prefilter_policy_proposals(id),
  updated_at timestamptz not null default now()
);

insert into public.prefilter_settings (id) values (1)
on conflict (id) do nothing;

alter table public.prefilter_policy_proposals enable row level security;
alter table public.prefilter_settings enable row level security;
revoke all on table public.prefilter_policy_proposals, public.prefilter_settings
  from anon, authenticated;
revoke all on sequence public.prefilter_policy_proposals_id_seq
  from anon, authenticated;
grant select, insert, update on table public.prefilter_policy_proposals
  to service_role;
grant select, update on table public.prefilter_settings to service_role;
grant usage, select on sequence public.prefilter_policy_proposals_id_seq
  to service_role;

create or replace function public.activate_prefilter_policy(
  p_proposal_id bigint,
  p_editor_user_id bigint
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected public.prefilter_policy_proposals%rowtype;
begin
  select * into selected
  from public.prefilter_policy_proposals
  where id = p_proposal_id and status = 'pending'
  for update;
  if not found then return false; end if;

  update public.prefilter_policy_proposals
  set status = 'superseded'
  where status = 'active';

  update public.prefilter_policy_proposals
  set status = 'active', decided_at = now(), decided_by = p_editor_user_id
  where id = selected.id;

  update public.prefilter_settings
  set learning_mode = false,
      current_policy_id = selected.id,
      decisions_at_last_proposal = selected.training_decisions,
      updated_at = now()
  where id = 1;
  return true;
end;
$$;

create or replace function public.reject_prefilter_policy(
  p_proposal_id bigint,
  p_editor_user_id bigint
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected public.prefilter_policy_proposals%rowtype;
begin
  select * into selected
  from public.prefilter_policy_proposals
  where id = p_proposal_id and status = 'pending'
  for update;
  if not found then return false; end if;

  update public.prefilter_policy_proposals
  set status = 'rejected', decided_at = now(), decided_by = p_editor_user_id
  where id = selected.id;

  update public.prefilter_settings
  set decisions_at_last_proposal = selected.training_decisions,
      updated_at = now()
  where id = 1;
  return true;
end;
$$;

revoke all on function public.activate_prefilter_policy(bigint,bigint)
  from public, anon, authenticated;
revoke all on function public.reject_prefilter_policy(bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.activate_prefilter_policy(bigint,bigint)
  to service_role;
grant execute on function public.reject_prefilter_policy(bigint,bigint)
  to service_role;

commit;
