-- Editor feedback state, versioned drafts, and transactional correction helpers.
begin;

alter table public.editor_queue
  add column if not exists revision integer not null default 1,
  add column if not exists telegram_chat_id bigint,
  add column if not exists telegram_message_id bigint,
  add column if not exists last_sent_at timestamp with time zone;

alter table public.editor_queue
  add constraint editor_queue_revision_positive check (revision > 0);

alter table public.ai_runs
  add column if not exists corrections_processed_count integer not null default 0,
  add column if not exists corrections_failed_count integer not null default 0;

create table public.editorial_feedback (
  id bigint generated by default as identity primary key,
  queue_id bigint not null references public.editor_queue(id) on delete cascade,
  article_id bigint not null references public.articles(id) on delete cascade,
  queue_revision integer not null,
  feedback_type text not null,
  status text not null default 'awaiting_comment',
  editor_comment text,
  telegram_chat_id bigint not null,
  telegram_user_id bigint not null,
  prompt_message_id bigint,
  source_title text,
  source_summary text,
  draft_title text,
  draft_text text,
  revised_title text,
  revised_text text,
  model text,
  attempts integer not null default 0,
  processing_started_at timestamp with time zone,
  error text,
  created_at timestamp with time zone not null default now(),
  submitted_at timestamp with time zone,
  processed_at timestamp with time zone,
  updated_at timestamp with time zone not null default now(),
  constraint editorial_feedback_revision_positive check (queue_revision > 0),
  constraint editorial_feedback_attempts_nonnegative check (attempts >= 0),
  constraint editorial_feedback_comment_length
    check (editor_comment is null or char_length(editor_comment) <= 2000),
  constraint editorial_feedback_type_valid check (
    feedback_type in ('approved', 'text_correction', 'topic_mismatch', 'other_rejection')
  ),
  constraint editorial_feedback_status_valid check (
    status in (
      'awaiting_comment',
      'pending_processing',
      'processing',
      'applied',
      'failed',
      'cancelled'
    )
  )
);

create unique index editorial_feedback_one_open_request
  on public.editorial_feedback (queue_id, queue_revision)
  where status in ('awaiting_comment', 'pending_processing', 'processing');

create unique index editorial_feedback_one_approval
  on public.editorial_feedback (queue_id, queue_revision)
  where feedback_type = 'approved';

create index editorial_feedback_pending_corrections
  on public.editorial_feedback (created_at, id)
  where feedback_type = 'text_correction' and status = 'pending_processing';

create index editorial_feedback_policy_history
  on public.editorial_feedback (created_at desc, id desc)
  where status = 'applied' and feedback_type in ('approved', 'topic_mismatch');

comment on table public.editorial_feedback is
  'Append-only editorial decisions and correction requests for Telegram candidates.';
comment on column public.editor_queue.revision is
  'Publication draft version; callback actions must match this value.';

alter table public.editorial_feedback enable row level security;
revoke all on table public.editorial_feedback from anon, authenticated;
grant select, insert, update on table public.editorial_feedback to service_role;
grant usage, select on sequence public.editorial_feedback_id_seq to service_role;

create or replace function public.submit_editorial_feedback(
  p_feedback_id bigint,
  p_editor_comment text
)
returns text
language plpgsql
security invoker
set search_path = ''
as $$
declare
  feedback_row public.editorial_feedback%rowtype;
  queue_row public.editor_queue%rowtype;
  clean_comment text;
  decision text;
begin
  clean_comment := left(btrim(coalesce(p_editor_comment, '')), 2000);
  if char_length(clean_comment) < 2 then
    raise exception 'editor comment is too short';
  end if;

  select *
    into feedback_row
    from public.editorial_feedback
   where id = p_feedback_id
     and status = 'awaiting_comment'
   for update;

  if not found then
    raise exception 'feedback request is not awaiting a comment';
  end if;

  select *
    into queue_row
    from public.editor_queue
   where id = feedback_row.queue_id
     and article_id = feedback_row.article_id
   for update;

  if not found
     or queue_row.revision <> feedback_row.queue_revision
     or queue_row.status <> 'awaiting_feedback' then
    raise exception 'queue item is not awaiting this feedback revision';
  end if;

  if feedback_row.feedback_type = 'text_correction' then
    decision := 'text_correction_requested';

    update public.editorial_feedback
       set editor_comment = clean_comment,
           status = 'pending_processing',
           submitted_at = now(),
           updated_at = now(),
           error = null
     where id = feedback_row.id;

    update public.editor_queue
       set status = 'correction_pending',
           reviewed_at = null
     where id = queue_row.id;
  else
    decision := feedback_row.feedback_type;

    update public.editorial_feedback
       set editor_comment = clean_comment,
           status = 'applied',
           submitted_at = now(),
           processed_at = now(),
           updated_at = now(),
           error = null
     where id = feedback_row.id;

    update public.editor_queue
       set status = 'rejected',
           reviewed_at = now()
     where id = queue_row.id;
  end if;

  update public.article_analysis
     set editor_decision = decision,
         editor_reason = clean_comment
   where article_id = feedback_row.article_id;

  update public.articles
     set editor_decision = decision,
         editor_reason = clean_comment
   where id = feedback_row.article_id;

  return case
    when feedback_row.feedback_type = 'text_correction' then 'correction_pending'
    else 'rejected'
  end;
end;
$$;

revoke all on function public.submit_editorial_feedback(bigint, text)
  from public, anon, authenticated;
grant execute on function public.submit_editorial_feedback(bigint, text)
  to service_role;

create or replace function public.claim_editorial_correction(
  p_feedback_id bigint
)
returns setof public.editorial_feedback
language sql
security invoker
set search_path = ''
as $$
  update public.editorial_feedback
     set status = 'processing',
         attempts = attempts + 1,
         processing_started_at = now(),
         updated_at = now(),
         error = null
   where id = p_feedback_id
     and feedback_type = 'text_correction'
     and status = 'pending_processing'
     and attempts < 3
  returning *;
$$;

revoke all on function public.claim_editorial_correction(bigint)
  from public, anon, authenticated;
grant execute on function public.claim_editorial_correction(bigint)
  to service_role;

create or replace function public.apply_editorial_correction(
  p_feedback_id bigint,
  p_expected_revision integer,
  p_title text,
  p_text text,
  p_model text
)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  feedback_row public.editorial_feedback%rowtype;
  queue_row public.editor_queue%rowtype;
  next_revision integer;
begin
  if char_length(btrim(coalesce(p_title, ''))) = 0
     or char_length(btrim(coalesce(p_text, ''))) = 0 then
    raise exception 'corrected publication cannot be empty';
  end if;

  select *
    into feedback_row
    from public.editorial_feedback
   where id = p_feedback_id
     and feedback_type = 'text_correction'
     and status = 'processing'
     and queue_revision = p_expected_revision
   for update;

  if not found then
    raise exception 'correction is not in processing state';
  end if;

  select *
    into queue_row
    from public.editor_queue
   where id = feedback_row.queue_id
     and article_id = feedback_row.article_id
     and revision = p_expected_revision
     and status = 'correction_pending'
   for update;

  if not found then
    raise exception 'queue revision is no longer awaiting this correction';
  end if;

  update public.article_analysis
     set telegram_title = left(btrim(p_title), 300),
         telegram_text = left(btrim(p_text), 4000),
         editor_decision = 'text_corrected',
         editor_reason = feedback_row.editor_comment,
         processed_at = now()
   where article_id = feedback_row.article_id;

  if not found then
    raise exception 'article analysis is missing';
  end if;

  next_revision := queue_row.revision + 1;

  update public.editor_queue
     set status = 'pending',
         revision = next_revision,
         reviewed_at = null,
         telegram_chat_id = null,
         telegram_message_id = null,
         last_sent_at = null
   where id = queue_row.id;

  update public.editorial_feedback
     set status = 'applied',
         revised_title = left(btrim(p_title), 300),
         revised_text = left(btrim(p_text), 4000),
         model = left(btrim(coalesce(p_model, '')), 100),
         processed_at = now(),
         updated_at = now(),
         processing_started_at = null,
         error = null
   where id = feedback_row.id;

  return next_revision;
end;
$$;

revoke all on function public.apply_editorial_correction(bigint, integer, text, text, text)
  from public, anon, authenticated;
grant execute on function public.apply_editorial_correction(bigint, integer, text, text, text)
  to service_role;

commit;
