-- Shadow-mode semantic predictions and leave-one-out retrieval support.
begin;

drop function if exists public.match_editorial_decisions(
  extensions.vector(512), text, integer, double precision
);

create function public.match_editorial_decisions(
  p_query_embedding extensions.vector(512),
  p_embedding_model text,
  p_match_count_per_type integer default 5,
  p_min_similarity double precision default 0.30,
  p_exclude_article_id bigint default null
)
returns table (
  feedback_id bigint,
  article_id bigint,
  feedback_type text,
  status text,
  editor_comment text,
  source_title text,
  source_summary text,
  draft_title text,
  draft_text text,
  created_at timestamptz,
  similarity double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  with candidates as (
    select
      f.id as feedback_id,
      f.article_id,
      f.feedback_type,
      f.status,
      f.editor_comment,
      f.source_title,
      f.source_summary,
      f.draft_title,
      f.draft_text,
      f.created_at,
      1 - (
        a.relevance_embedding operator(extensions.<=>) p_query_embedding
      ) as similarity,
      row_number() over (
        partition by f.feedback_type
        order by
          a.relevance_embedding operator(extensions.<=>) p_query_embedding,
          f.created_at desc,
          f.id desc
      ) as label_rank
    from public.editorial_feedback as f
    join public.articles as a on a.id = f.article_id
    where f.status = 'applied'
      and f.feedback_type in ('approved', 'topic_mismatch')
      and (p_exclude_article_id is null or f.article_id <> p_exclude_article_id)
      and a.relevance_embedding is not null
      and a.relevance_embedding_model = p_embedding_model
      and 1 - (
        a.relevance_embedding operator(extensions.<=>) p_query_embedding
      ) >= p_min_similarity
  )
  select
    candidates.feedback_id,
    candidates.article_id,
    candidates.feedback_type,
    candidates.status,
    candidates.editor_comment,
    candidates.source_title,
    candidates.source_summary,
    candidates.draft_title,
    candidates.draft_text,
    candidates.created_at,
    candidates.similarity
  from candidates
  where candidates.label_rank <= least(greatest(p_match_count_per_type, 1), 10)
  order by candidates.similarity desc, candidates.created_at desc;
$$;

revoke all on function public.match_editorial_decisions(
  extensions.vector(512), text, integer, double precision, bigint
) from public, anon, authenticated;
grant execute on function public.match_editorial_decisions(
  extensions.vector(512), text, integer, double precision, bigint
) to service_role;

create table public.editorial_memory_predictions (
  id bigint generated by default as identity primary key,
  article_id bigint not null unique
    references public.articles(id) on delete cascade,
  embedding_model text not null,
  mode text not null default 'shadow',
  predicted_feedback_type text,
  confidence double precision not null default 0,
  approval_score double precision not null default 0,
  rejection_score double precision not null default 0,
  approval_examples integer not null default 0,
  rejection_examples integer not null default 0,
  neighbors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint editorial_memory_prediction_mode_valid
    check (mode in ('shadow', 'active')),
  constraint editorial_memory_prediction_label_valid
    check (
      predicted_feedback_type is null
      or predicted_feedback_type in ('approved', 'topic_mismatch', 'uncertain')
    )
);

comment on table public.editorial_memory_predictions is
  'Auditable semantic-memory predictions. Shadow mode never blocks an article.';

alter table public.editorial_memory_predictions enable row level security;
revoke all on table public.editorial_memory_predictions
  from public, anon, authenticated;
revoke all on sequence public.editorial_memory_predictions_id_seq
  from public, anon, authenticated;
grant select, insert, update on table public.editorial_memory_predictions
  to service_role;
grant usage, select on sequence public.editorial_memory_predictions_id_seq
  to service_role;

commit;
