-- Run the full pipeline from Supabase Cron instead of GitHub's best-effort
-- schedule event. The GitHub token is read only from Supabase Vault.
begin;

-- These extensions are available in the project but are not enabled yet.
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net;

create schema if not exists private;

revoke all on schema private from public, anon, authenticated;
grant usage on schema private to postgres, service_role;

create table if not exists private.pipeline_dispatch_log (
  id bigint generated by default as identity primary key,
  invoked_at timestamptz not null default now(),
  local_time time not null,
  status text not null,
  request_id bigint,
  detail text,
  constraint pipeline_dispatch_log_status_valid
    check (status in (
      'skipped_outside_window',
      'skipped_no_token',
      'queued',
      'error'
    ))
);

create index if not exists pipeline_dispatch_log_invoked_at_idx
  on private.pipeline_dispatch_log (invoked_at desc, id desc);

alter table private.pipeline_dispatch_log enable row level security;
revoke all on table private.pipeline_dispatch_log from public, anon, authenticated;
grant select on table private.pipeline_dispatch_log to service_role;
grant usage, select on sequence private.pipeline_dispatch_log_id_seq to service_role;

create or replace function private.dispatch_full_news_pipeline()
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, private, vault, net
as $function$
declare
  brussels_now timestamp without time zone;
  brussels_time time;
  github_token text;
  request_id bigint;
begin
  brussels_now := timezone('Europe/Brussels', now());
  brussels_time := brussels_now::time;

  -- Cron runs at UTC candidate slots; this gate makes the exact operating
  -- window stable across CET and CEST: 09:07 through 00:37 Brussels time.
  if not (
    brussels_time >= time '09:07'
    or brussels_time <= time '00:37'
  ) then
    insert into private.pipeline_dispatch_log (local_time, status, detail)
    values (
      brussels_time,
      'skipped_outside_window',
      format('Outside 09:07-00:37 Europe/Brussels at %s', brussels_now)
    );
    return null;
  end if;

  select decrypted_secret
    into github_token
    from vault.decrypted_secrets
   where name = 'github_actions_token'
   limit 1;

  if coalesce(btrim(github_token), '') = '' then
    insert into private.pipeline_dispatch_log (local_time, status, detail)
    values (
      brussels_time,
      'skipped_no_token',
      'Vault secret github_actions_token is not configured'
    );
    return null;
  end if;

  select net.http_post(
    url := 'https://api.github.com/repos/iazenin88-lang/belgium-news-bot/actions/workflows/full_pipeline.yml/dispatches',
    headers := jsonb_build_object(
      'Accept', 'application/vnd.github+json',
      'Authorization', 'Bearer ' || github_token,
      'Content-Type', 'application/json',
      'User-Agent', 'belgium-news-supabase-cron',
      'X-GitHub-Api-Version', '2022-11-28'
    ),
    body := jsonb_build_object('ref', 'main'),
    timeout_milliseconds := 5000
  )
    into request_id;

  insert into private.pipeline_dispatch_log (
    local_time,
    status,
    request_id,
    detail
  )
  values (
    brussels_time,
    'queued',
    request_id,
    'GitHub workflow_dispatch queued through pg_net'
  );

  return request_id;
exception
  when others then
    insert into private.pipeline_dispatch_log (local_time, status, detail)
    values (
      coalesce(brussels_time, timezone('Europe/Brussels', now())::time),
      'error',
      sqlerrm
    );
    raise;
end;
$function$;

revoke all on function private.dispatch_full_news_pipeline()
  from public, anon, authenticated;
grant execute on function private.dispatch_full_news_pipeline()
  to postgres, service_role;

-- Candidate slots are every 30 minutes at :07 and :37, 07:00-23:59 UTC.
-- The function above applies the Brussels operating-window gate.
select cron.schedule(
  'full-news-pipeline-dispatch',
  '7,37 7-23 * * *',
  'select private.dispatch_full_news_pipeline();'
);

commit;
